driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-5.11-i386
  - name: centos-6.7
  - name: centos-6.7-i386
  - name: fedora-21

suites:
  - name: default
    run_list:
      - recipe[yum::default]
      - recipe[yum_test::test_repo]
